#!/usr/bin/env bash

GNOSTR_XQ=$(which gnostr-xq)
type -P $GNOSTR_XQ &>/dev/null || cargo install gnostr-xq
GNOSTR_REFLOG=$(which gnostr-reflog)
type -P $GNOSTR_REFLOG  &>/dev/null || cargo install gnostr-bins
GNOSTR_POST_EVENT=$(which gnostr-post-event)
type -P $GNOSTR_POST_EVENT  &>/dev/null || cargo install gnostr-bins
GNOSTR_GET_RELAYS=$(which gnostr-get-relays)
type -P $GNOSTR_GET_RELAYS  &>/dev/null || cargo install gnostr-bins

help(){

echo "USAGE:"
echo    "gnostr-syndicate wss://e.nos.lol 1"
echo    "gnostr-syndicate --list 1"
exit;
}

if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    help
fi

some_path=$PWD
REPO=$(basename $some_path)
PARENT_REPO=$(basename $(dirname $some_path))
##GRANDPARENT_REPO=$(basename $(dirname $(dirname $some_path)))

IS_REPO=$(git rev-parse --is-inside-work-tree)
if $IS_REPO;then
REPO=$(basename $some_path);
else
REPO=$(basename $(dirname $some_path));
fi

BRANCH=`git rev-parse --abbrev-ref HEAD` #&& echo $BRANCH
GIT_ORIGIN=$(git config --get remote.origin.url)

RELAY=${1:-wss://e.nos.lol}
POW=${2:-1}
GNOSTR_WEEBLE=$(gnostr-weeble)
WEEBLE=${3:-$GNOSTR_WEEBLE}
BLOCK=${4:-$(gnostr-blockheight)}
WOBBLE=${5:-$(gnostr-wobble)}
count=0;
new_count=0;
INIT_COMMIT=$(git rev-list --all --max-parents=0)

for commit_hash in $(git rev-list $BRANCH);do

padded_commit_hash=`printf '%064s' "$commit_hash"`
count=$((count+1))
done
export COUNT=$count

for commit_hash in $($GNOSTR_REFLOG);do

PARENT=$(git rev-parse $commit_hash^1)
padded_parent_hash=`printf '%064s' "$PARENT"`
padded_commit_hash=`printf '%064s' "$commit_hash"`
export NEW_COUNT=$new_count
PARENT_ID=$(gnostr --sec $padded_parent_hash | $GNOSTR_XQ .pubkey)
ID=$(gnostr --sec $padded_commit_hash | gnostr-xq .pubkey)
PARENT_ID=${PARENT_ID//\"/}
ID=${ID//\"/}


if [[ "$1" == "--list" ]];
then
for relays in $($GNOSTR_GET_RELAYS -s);
do
echo $relays
gnostr --sec $padded_commit_hash \
--pow $POW \
-t gnostr \
--tag repo $REPO \
--tag relay $relays \
--tag r $relays \
--tag branch $BRANCH \
--tag origin $GIT_ORIGIN \
--tag weeble $WEEBLE \
--tag block $BLOCK \
--tag wobble $WOBBLE \
-t $padded_commit_hash \
--tag commit $commit_hash \
--tag parent $PARENT \
--tag p $PARENT_ID \
--content "$(git show $commit_hash || exit)" | $GNOSTR_POST_EVENT $relays || echo "$commit_hash failed!"
done
else
gnostr --sec $padded_commit_hash \
--pow $POW \
-t gnostr \
--tag repo $REPO \
--tag relay $RELAY \
--tag r $RELAY \
--tag branch $BRANCH \
--tag origin $GIT_ORIGIN \
--tag weeble $WEEBLE \
--tag block $BLOCK \
--tag wobble $WOBBLE \
-t $padded_commit_hash \
--tag commit $commit_hash \
--tag parent $PARENT \
--tag p $PARENT_ID \
--content "$(git show $commit_hash || exit)" | $GNOSTR_POST_EVENT $RELAY || echo "$commit_hash failed!"
fi

if [[ "$commit_hash" == "$INIT_COMMIT" ]]; then
exit;
fi
new_count=$((new_count+1))
done
exit;
