#!/usr/bin/env bash
#

if [[ $1 = "-h" ]] || [[ $1 = "--help" ]]; then

  #echo ""help""
  printf  "     \ngnostr-set-relays\n\n"
  printf  "     gnostr-set-relays -h  --help\n"
  printf  "     gnostr-set-relays -v  --version\n"
  printf  "     gnostr-set-relays -vv --verbose\n"

  printf  "     git config --get gnostr.relay-0\n"
  printf  "     git config --get gnostr.relay-1\n"
  printf  "     git config --get gnostr.relay-#\n"

exit;
fi
if [[ $1 = "-v" ]] || [[ $1 = "--version" ]]; then

  echo ""v0.0.0""

exit;
fi
declare count=0
RELAYS=$(gnostr-get-relays -s)
git config --global --replace gnostr.relays "$RELAYS";
#echo $RELAYS
for relay in $RELAYS; do
#if [[ $1 = "-vv" ]] || [[ $1 = "--verbose" ]]; then
#echo "gnostr.relay-$count=$relay"
#fi
git config --global --replace gnostr.relay-$count "$relay";
count=$((count + 1))
#echo $count
done
if [[ $1 = "-vv" ]] || [[ $1 = "--verbose" ]]; then
    #git config --global -l | grep gnostr.relays
    git config --global -l | grep gnostr.relay-
fi
