#!/usr/bin/env bash
#

# Normalize `open` across Linux, macOS, and Windows.
# This is needed to make the `o` function (see below) cross-platform.
if [ ! $(uname -s) = 'Darwin' ]; then
	if grep -q Microsoft /proc/version; then
		# Ubuntu on Windows using the Linux subsystem
		alias open='explorer.exe';
	else
		alias open='xdg-open';
	fi
fi

# `o` with no arguments opens the current directory, otherwise opens the given
# location
function o() {
	if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}


PORT=80 && export $PORT

if [[ $1 = "-h" ]] || [[ $1 = "--help" ]]; then

  echo ""help""

exit;
fi
if [[ $1 = "-v" ]] || [[ $1 = "--version" ]]; then

  echo ""v0.0.2""

exit;
fi
if [[ $1 = "-p" ]] || [[ $1 = "--port" ]]; then

  PORT=$2 && export $PORT

fi

echo PID=$$
gnostr-web --http-address=0.0.0.0 --http-port=$PORT --deploy-path=/web --docroot=. & \
  $(which open) http://localhost:$PORT
