#!/usr/bin/env bash
PORT=80 && export $PORT

if [[ $1 = "-h" ]] || [[ $1 = "--help" ]]; then

  echo ""help""

exit;
fi
if [[ $1 = "-v" ]] || [[ $1 = "--version" ]]; then

  echo ""v0.0.2""

exit;
fi
if [[ $1 = "-p" ]] || [[ $1 = "--port" ]]; then

  PORT=$2 && export PORT

fi


gnostr-web --http-address=0.0.0.0 --http-port=$PORT --deploy-path=/web --docroot=. & \
  $(shell which open) http://0.0.0.0:$PORT
